# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

JaccardCPP <- function(data1, data2) {
    .Call(`_similarity_JaccardCPP`, data1, data2)
}

rcpp_hello_world <- function() {
    .Call(`_similarity_rcpp_hello_world`)
}

